services:
  aspire-dashboard:
    container_name: "aspire-dashboard"
    image: "mcr.microsoft.com/dotnet/aspire-dashboard:8.0"
    environment:
      DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS: "true"
    ports:
    - target: 18888
      published: 18888
    restart: unless-stopped
  MessageBus:
    container_name: "MessageBus"
    image: "docker.io/library/rabbitmq:3.13-management"
    environment:
      RABBITMQ_DEFAULT_USER: "serviceUser"
      RABBITMQ_DEFAULT_PASS: "securePassword123"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://aspire-dashboard:18889"
      OTEL_SERVICE_NAME: "MessageBus"
    ports:
    - target: 5672
      published: 16081
    - target: 15672
      published: 15672
    restart: unless-stopped
  MSSQL:
    container_name: "MSSQL"
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "securePassword123"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://aspire-dashboard:18889"
      OTEL_SERVICE_NAME: "MSSQL"
    ports:
    - target: 1433
      published: 16082
    restart: unless-stopped
  Postgres:
    container_name: "Postgres"
    image: "docker.io/library/postgres:16.2"
    environment:
      POSTGRES_HOST_AUTH_METHOD: "scram-sha-256"
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
      POSTGRES_USER: "serviceUser"
      POSTGRES_PASSWORD: "securePassword123"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://aspire-dashboard:18889"
      OTEL_SERVICE_NAME: "Postgres"
    ports:
    - target: 5432
      published: 16083
    restart: unless-stopped
